package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/nabishec/ozon_habr_api/graph/model"
	internalmodel "github.com/nabishec/ozon_habr_api/internal/model"
	"github.com/rs/zerolog/log"
)

// AddPost is the resolver for the addPost field.
func (r *mutationResolver) AddPost(ctx context.Context, postInput model.NewPost) (*model.Post, error) {
	const op = "graph.AddPost()"

	log.Debug().Msgf("%s start", op)

	newPost := toInternalModel(&postInput)
	post, err := r.PostMutation.AddPost(newPost)

	if err != nil {
		log.Debug().Msgf("%s end with error", op)
		return nil, err
	}

	log.Debug().Msgf("%s end", op)
	return fromInternalModel(post), err
}

func toInternalModel(postInput *model.NewPost) *internalmodel.NewPost {
	return &internalmodel.NewPost{
		AuthorID:        postInput.AuthorID,
		Title:           postInput.Title,
		Text:            postInput.Text,
		CommentsEnabled: postInput.CommentsEnabled,
	}
}

func fromInternalModel(postInput *internalmodel.Post) *model.Post {
	return &model.Post{
		ID:              postInput.ID,
		AuthorID:        postInput.AuthorID,
		Title:           postInput.Title,
		Text:            postInput.Text,
		CommentsEnabled: postInput.CommentsEnabled,
		CreateDate:      postInput.CreateDate,
	}
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, commentInput model.NewComment) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: AddComment - addComment"))
}

// EnableComment is the resolver for the enableComment field.
func (r *mutationResolver) EnableComment(ctx context.Context, postID int64, authorID uuid.UUID, commentsEnabled bool) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: EnableComment - enableComment"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, postID int64) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: Post - post"))
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int64) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentAdded - commentAdded"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
